# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 210feafeb0852e8d2d97729b97abfdc323bfd4cfbc761c2728ccb86fccfc03691883720d6b7c01a1a731fa88c2a0dcc5e03a7235f032f1a6cc00c58c33fefcff

test:
  secret_key_base: ecc2f55f1fa694a5d9cff1d9160720a8d751b8ef00cab3226a16f02aeb6699278b26c05dfd10f1cf18b469abf617db5963eb56caf8bb37631eddba3ff7d884e3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
